Allow 1 Tick of Lag to Update the Timer Logicate Renderer
Luligabi1/Logicates pull request #7
Opened 2023-10-10 00:26 UTC by ChampionAsh5357

Closes #1 

The timer is normally set to power on and off the block state on a single tick. This means that render updates do not happen to the block unless directly forced (like in the case of neighbor updates). Additionally, while Minecraft can handle multiple block changes to the same position in a single tick, it is generally advised to allow one tick of downtime to avoid any client desyncs (I should note that some systems are updated every 2-3 ticks, so those scenarios would cause unseen behavior quite often). To address both of these issues, the timer outputs a signal for a single tick, allowing the block to rerender in time.

2023-10-10 20:50 UTC, Luligabi1 requested changes

2023-10-10 20:50 UTC, Luligabi1 commented on src/main/java/me/luligabi/logicates/common/block/logicate/inputless/timer/TimerLogicateBlockEntity.java
> +        if (blockEntity.ticks == 1) {
```suggestion
        if(blockEntity.ticks == 1) {
```

I feel bad for being this nitpicky, hopefully you should be able to just have Github do the job of commiting this lol

2023-10-17 18:18 UTC, ChampionAsh5357 commented
My bad, sorry for the late reply. My phone chose not to notify me.

2023-10-17 19:17 UTC, Luligabi1 commented
> My bad, sorry for the late reply. My phone chose not to notify me.

No problems, thanks for your contribution!

2023-10-17 19:19 UTC, merged